//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportTransaction
    {
        public int TransactionID { get; set; }
        public System.Guid BatchID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TotalRows { get; set; }
        public Nullable<int> ProcessedRows { get; set; }
        public Nullable<int> FailedRows { get; set; }
        public string Outcome { get; set; }
        public Nullable<System.DateTime> LoggedAt { get; set; }
    }
}
